# -*- coding: utf-8 -*-
"""Kalkulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12qVdLnrET-8dWnkLg2knJP6fI3j_oH8p
"""

import math
# Menu 1

print("     MENU    ")
print("--------------")
print("1. Pertambahan")
print("2. Pengurangan")
print("3. Perkalian")
print("4. Pembagian")
print("5. Modulus")
print("6. Perpangkatan")
print("--------------")

# Input

pilih = int(input("Masukan angka sesuai menu yang ingin digunakan: "))

# Input 2

if pilih in [1,2,3,4,5,6]:
    x = float(input("Masukkan angka pertama: "))
    y = float(input("Masukkan angka kedua: "))
elif pilih == 7:
    x = float(input("Masukkan angka (dalam radian): "))

# Logic
def penjumlahan(x,y):
  return x + y
def Pengurangan(x,y):
  return x - y
def Perkalian(x,y):
  return x * y
def Pembagian(x,y):
  return x / y
def Modulus(x,y):
  return x % y
def Perpangkatan(x,y):
  return x ** y

# Kondisi Menu

if pilih == 1:
  print(f"Hasil: {penjumlahan(x,y)}")
elif pilih == 2:
  print(f"Hasil: {Pengurangan(x,y)}")
elif pilih == 3:
  print(f"Hasil: {Perkalian(x,y)}")
elif pilih == 4:
  print(f"Hasil: {Pembagian(x,y)}")
elif pilih == 5:
  print(f"Hasil: {Modulus(x,y)}")
elif pilih == 6:
  print(f"Hasil: {Perpangkatan(x,y)}")